### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by nreilly** [IdeaSynthesis/letsencrypt-dns01-hooks#5]
Using the current version, I'm getting the below error at the end of updating/requesting certificates with dehydrated. This wasn't happening before the recent change to add specified name servers for validation. It happens both with the dehydrated -c call method, and the one specified in your readme. Certificates continue to be generated fine though.

$ dehydrated -c
# INFO: Using main config file /Users/blah/Documents/certs/config
Processing something.example.com
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Sep  9 12:48:00 2017 GMT (Longer than 30 days). Skipping renew!
Processing somethingelse.example.com
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Sep 10 04:34:00 2017 GMT (Longer than 30 days). Skipping renew!
panic: runtime error: index out of range

goroutine 1 [running]:
main.main()
	/Users/blah/Documents/code/go/src/github.com/IdeaSynthesis/letsencrypt-dns01-hooks/hook.go:59 +0x4d76

**Comment by fomojola** [comment]
Ah, hadn't looked at dehydrated in a while: they added a number of new calls (exit_hook and request_failure) that don't call the hook with the same number of arguments as the deploy_challenge and clean_challenge calls. I've moved all the argument parsing into the individual call handlers: let me know if that works.

**Comment by nreilly** [comment]
No more panics! Thanks again for your quick responses.

**Comment by nreilly** [comment]
No more panics! Thanks again for your quick responses.
